Repository IqraMahmood/HACKTOBERFEST-Python, pull requests merged in 2022-10, with the labels that each got.

#2 Python Basic programs
  01-first-programe.py
  02_operator.py
Labels: good first issue, hacktoberfest-accepted

#4 Python sorting
  quick_sort.py
Labels: hacktoberfest-accepted

#5 bubble_sort.py
  bubble_sort.py
Labels: hacktoberfest-accepted

#6 Create List.py
  List.py
Labels: hacktoberfest-accepted

#8 Add random password generator
  random_password_generator.py
Labels: good first issue
